### ISSUE TITLE
Hardware revision is not supported for Raspbery pi 3 with hardware revision a32082

### ISSUE THREAD

**Issue by kingofleaves** [jgarff/rpi_ws281x#519]
HI, I have a similar problem as issue #364 , with my Raspberry Pi 3B.
Here is the revision code output: 
```
pi@raspberrypi:~ $ cat /proc/device-tree/model 
Raspberry Pi 3 Model B Rev 1.2
pi@raspberrypi:~ $ cat /proc/cpuinfo | grep Revision
Revision	: a32082
```
And here is the error message from which it tells me Hardware Revision not supported:
```
pi@raspberrypi:~/rpi-ws281x-python/examples $ python3 strandtest.py 
Traceback (most recent call last):
  File "/home/pi/rpi-ws281x-python/examples/strandtest.py", line 97, in <module>
    strip.begin()
  File "/usr/local/lib/python3.9/dist-packages/rpi_ws281x/rpi_ws281x.py", line 131, in begin
    raise RuntimeError('ws2811_init failed with code {0} ({1})'.format(resp, str_resp))
RuntimeError: ws2811_init failed with code -3 (Hardware revision is not supported)
Segmentation fault
```
Can anyone help with this? 
Thanks!

**Comment by Gadgetoid** [comment]
If you have time, please try the pre-release version here: https://test.pypi.org/project/rpi-ws281x/5.0.0/
