### ISSUE TITLE
Led's not working as expected

### ISSUE THREAD

**Issue by ebeng** [jgarff/rpi_ws281x#87]
Hi Gents,

I would like to thank you, what great you did with writing this!!! I love it!!!
I'm trying to build my own word Clock with all the info i got from here and there.

There is only one thing that im struggling now at this moment.
I have soldered 16 leds WS2812B. I just cant find to get them work, with the test function and strandtest.py

I did setup it, like this here https://learn.adafruit.com/neopixels-on-raspberry-pi?view=all

Also i did add a 1000uF parallel to the 5+ and grnd to the input of the leds and after the signal data out from the level shifter i added a 280Ohm. 
This all to protect the led's, as described here https://learn.sparkfun.com/tutorials/ws2812-breakout-hookup-guide

What is happening is the next:
- If i touch the Data PIN with the GND pin of my multimeter, it looks like that the leds starts to blink every colort etc and if i let it go it will stay burning in 1 mode....

- I disconnect the data pin from the raspberry to the leds, the same things occur, it start blinking etc, when touching the Data Pin.

This is the strandtest.py config:

LED_COUNT      = 16      # Number of LED pixels.
LED_PIN        = 18      # GPIO pin connected to the pixels (must support PWM!).
LED_FREQ_HZ    = 800000  # LED signal frequency in hertz (usually 800khz)
LED_DMA        = 5       # DMA channel to use for generating signal (try 5)
LED_BRIGHTNESS = 255      # Set to 0 for darkest and 255 for brightest
LED_INVERT     = False   # True to invert the signal (when using NPN transistor level shift)

Even if i change the LED_Invert to True it does the same !?

also noticed the next when breaking the code:

root@xx-clocl:~/rpi_ws281x/python/examples# sudo python strandtest.py
Press Ctrl-C to quit.
^CTraceback (most recent call last):
  File "strandtest.py", line 98, in <module>
    theaterChaseRainbow(strip)
  File "strandtest.py", line 75, in theaterChaseRainbow
    strip.setPixelColor(i+q, 0)
KeyboardInterrupt
root@xx-clocl:~/rpi_ws281x/python/examples#

root@raspberrypi-clocl:~/rpi_ws281x/python/examples# cat /proc/cpuinfo
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 2.00
Features        : half thumb fastmult vfp edsp java tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2708
Revision        : 0010
Serial          : 00000000e233fae0

I'm really lost....

**Comment by ebeng** [comment]
After writing this all, i was really pissed why it did not work :)

Looks like i messed up with the Pin numbers etc.... The numbering of these PINS are really pretty messy....

all the names etc..... GPIO pin 18 looks to be Pin12 etc.... pfffffff
